version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 3
    groups:
      python-dev:
        patterns:
          - "*"
        exclude-patterns:
          - "editables"
          - "openai-harmony"
          - "ruff"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
