from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import get_args

from scripts import smoke_shadow_installed
from scripts.check_readme_visuals import (
    contrast_ratio,
    project_runtime_metadata_digest,
    runtime_source_digest,
    validate_evidence_manifest,
    validate_markdown_images,
    validate_readme_assets,
    validate_svg_text,
)

from saliencegate.shadow import ATIFProfile
from saliencegate.shadow.report import _SUPPORTED_SIGNAL_TYPES, ShadowRunReport
from saliencegate.shadow.trace import MAX_SHADOW_TRACE_ROWS

ROOT = Path(__file__).parents[1]
MANIFEST = Path("benchmarks/shadow_trace/reference-macos-26.5.2-arm64-cpython-3.12.3.manifest.json")
REPORT = Path("benchmarks/shadow_trace/reference-macos-26.5.2-arm64-cpython-3.12.3.json")
ASSETS = {
    "pipeline": Path("docs/assets/readme/pipeline.svg"),
    "atif": Path("docs/assets/readme/atif-example-results.svg"),
    "reference": Path("docs/assets/readme/reference-run.svg"),
}


def _svg(body: str, *, labelledby: str = "sample-title sample-desc") -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 600"
  role="img" aria-labelledby="{labelledby}">
  <title id="sample-title">Reference benchmark</title>
  <desc id="sample-desc">Measured memory and SQLite results</desc>
  <rect width="1600" height="600" fill="#f6f1e8"/>
  <text x="40" y="60" fill="#22211f" font-size="32">{body}</text>
</svg>"""


def test_reference_evidence_manifest_binds_every_measured_input() -> None:
    assert validate_evidence_manifest(ROOT, MANIFEST) == ()
    count, digest = runtime_source_digest(ROOT)
    assert count == 188
    assert digest == "0ada8edc62dc22153ad46f65c7df35df3a2fb247031fb77784b2d4a86a5ece8d"


def test_evidence_metadata_binding_ignores_editorial_packaging_fields(tmp_path: Path) -> None:
    source = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(source, encoding="utf-8")
    baseline = project_runtime_metadata_digest(tmp_path)

    pyproject.write_text(
        source.replace(
            'readme = "docs/package-description.md"',
            'readme = "README-for-package-index.md"',
        ),
        encoding="utf-8",
    )
    assert project_runtime_metadata_digest(tmp_path) == baseline

    pyproject.write_text(
        source.replace('"pydantic>=2.11,<3"', '"pydantic>=2.12,<3"'),
        encoding="utf-8",
    )
    assert project_runtime_metadata_digest(tmp_path) != baseline


def test_live_readme_asset_set_passes_the_standalone_checker_contract() -> None:
    assert validate_readme_assets(ROOT) == ()


def test_svg_validator_accepts_a_minimal_accessible_editorial_asset() -> None:
    assert (
        validate_svg_text(
            Path("docs/assets/readme/reference-run.svg"),
            _svg("Five measured runs"),
            required_text=("reference", "memory", "sqlite"),
        )
        == ()
    )


def test_svg_validator_rejects_active_external_and_generator_content() -> None:
    unsafe = _svg("Five measured runs").replace(
        "</svg>",
        '<script>alert(1)</script><image href="data:image/png;base64,AAAA"/></svg>',
    )
    unsafe = "<!-- Generated by Example Designer -->\n" + unsafe

    findings = validate_svg_text(
        Path("docs/assets/readme/reference-run.svg"),
        unsafe,
        required_text=("reference", "memory", "sqlite"),
    )

    assert any("comment" in finding for finding in findings)
    assert any("generator" in finding for finding in findings)
    assert any("forbidden element" in finding for finding in findings)
    assert any("embedded or external resource" in finding for finding in findings)


def test_svg_validator_rejects_empty_or_disconnected_accessibility_text() -> None:
    empty = _svg("Five measured runs", labelledby="sample-title missing-desc").replace(
        "Measured memory and SQLite results", "   "
    )

    findings = validate_svg_text(
        Path("docs/assets/readme/reference-run.svg"),
        empty,
        required_text=("reference", "memory", "sqlite"),
    )

    assert any("aria-labelledby" in finding for finding in findings)
    assert any("non-empty" in finding for finding in findings)
    assert any("asset-specific" in finding for finding in findings)


def test_svg_validator_rejects_small_text_and_event_handlers() -> None:
    unsafe = _svg("Five measured runs").replace('font-size="32"', 'font-size="18" onclick="x"')

    findings = validate_svg_text(
        Path("docs/assets/readme/reference-run.svg"),
        unsafe,
        required_text=("reference", "memory", "sqlite"),
    )

    assert any("28 SVG units" in finding for finding in findings)
    assert any("event handler" in finding for finding in findings)


def test_contrast_calculation_freezes_the_editorial_palette_boundary() -> None:
    assert contrast_ratio("#22211f", "#f6f1e8") >= 4.5
    assert contrast_ratio("#777777", "#f6f1e8") < 4.5


def test_markdown_images_must_be_local_and_have_meaningful_alt_text() -> None:
    valid = "![Five-run memory and SQLite reference](docs/assets/readme/reference-run.svg)"
    assert validate_markdown_images(Path("README.md"), valid) == ()

    external = "![Benchmark](https://example.test/chart.svg)"
    generic = "![Chart](docs/assets/readme/reference-run.svg)"
    external_findings = validate_markdown_images(Path("README.md"), external)
    generic_findings = validate_markdown_images(Path("README.md"), generic)
    assert any("external image" in finding for finding in external_findings)
    assert any("meaningful alt text" in finding for finding in generic_findings)


def _asset(name: str, *required_text: str) -> tuple[str, ET.Element]:
    path = ROOT / ASSETS[name]
    assert path.is_file(), f"missing {ASSETS[name]}"
    text = path.read_text(encoding="utf-8")
    assert validate_svg_text(ASSETS[name], text, required_text=required_text) == ()
    root = ET.fromstring(text)
    assert root.get("viewBox", "").split()[2] == "1600"
    assert root.get("width") == "100%"
    return text, root


def _metrics(root: ET.Element) -> dict[str, str]:
    metrics: dict[str, str] = {}
    for element in root.iter():
        metric = element.get("data-metric")
        if metric is None:
            continue
        assert metric not in metrics
        metrics[metric] = " ".join("".join(element.itertext()).split())
    return metrics


def test_pipeline_visual_is_bound_to_the_current_shadow_contract() -> None:
    text, root = _asset("pipeline", "shadow", "missing suffix", "provenance report")
    assert len(ATIFProfile) == 2
    assert len(_SUPPORTED_SIGNAL_TYPES) == 4
    assert get_args(ShadowRunReport.model_fields["model_calls"].annotation) == (0,)
    assert get_args(ShadowRunReport.model_fields["decision_authority"].annotation) == (False,)
    assert _metrics(root) == {
        "pipeline.profile_count": str(len(ATIFProfile)),
        "pipeline.detector_count": str(len(_SUPPORTED_SIGNAL_TYPES)),
        "pipeline.max_records": f"{MAX_SHADOW_TRACE_ROWS:,}",
        "pipeline.model_calls": "0",
        "pipeline.decision_authority": "false",
    }
    folded = " ".join(text.casefold().split())
    assert "no-op when complete" in folded
    assert "authenticated ledger" in folded
    assert "content-addressed provenance report" in folded
    assert "authenticated report" not in folded


def test_atif_visual_matches_the_two_public_synthetic_examples() -> None:
    text, root = _asset("atif", "codex", "terminus", "synthetic")
    codex = smoke_shadow_installed._PUBLIC_ATIF_EXPECTATIONS["harbor-codex/v1"]
    terminus = smoke_shadow_installed._PUBLIC_ATIF_EXPECTATIONS["harbor-terminus-2/v1"]
    assert _metrics(root) == {
        "codex.actions": str(codex.mapped_action_count),
        "codex.outcomes": str(codex.mapped_structured_outcome_count),
        "codex.records": str(codex.mapped_record_count),
        "codex.flagged": str(codex.flagged_count),
        "codex.outcome_authority": codex.outcome_evidence_authority,
        "terminus.actions": str(terminus.mapped_action_count),
        "terminus.outcomes": str(terminus.mapped_structured_outcome_count),
        "terminus.records": str(terminus.mapped_record_count),
        "terminus.flagged": str(terminus.flagged_count),
        "terminus.outcome_authority": terminus.outcome_evidence_authority,
        "examples.producer_authentication": "none",
        "examples.root_segment_only": "true",
        "examples.complete_session": "false",
    }
    assert "synthetic, not a quality comparison" in " ".join(text.casefold().split())


def test_reference_visual_matches_every_tracked_measurement_and_budget() -> None:
    _text, root = _asset("reference", "memory", "sqlite", "local reference run")
    report = json.loads((ROOT / REPORT).read_text(encoding="utf-8"))
    expected: dict[str, str] = {}
    for backend in ("memory", "sqlite"):
        result = report["backends"][backend]
        for ordinal, measurement in enumerate(result["measurements"], start=1):
            expected[f"{backend}.duration.{ordinal}"] = str(measurement["duration_seconds"])
        expected[f"{backend}.median"] = str(result["median_seconds"])
        expected[f"{backend}.time_budget"] = str(result["median_budget_seconds"])
        expected[f"{backend}.peak_rss"] = str(result["maximum_peak_rss_mib"])
        expected[f"{backend}.rss_budget"] = str(result["peak_rss_budget_mib"])
    expected.update(
        {
            "environment.platform": report["metadata"]["platform"],
            "environment.python": (
                f"{report['metadata']['python_implementation']} "
                f"{report['metadata']['python_version']}"
            ),
            "environment.cores": str(report["metadata"]["logical_core_count"]),
            "environment.memory_mib": str(report["metadata"]["memory_capacity_mib"]),
            "environment.runner_image": report["metadata"]["runner_image"],
        }
    )
    assert _metrics(root) == expected
    visual_text = " ".join("".join(root.itertext()).split())
    for backend in ("memory", "sqlite"):
        ratio = str(report["backends"][backend]["scaling_ratio_250_to_1000"])
        assert ratio not in visual_text


def test_visual_palette_uses_text_and_shape_contrast_without_color_only_labels() -> None:
    for name, required in (
        ("pipeline", ("shadow",)),
        ("atif", ("synthetic",)),
        ("reference", ("local reference run",)),
    ):
        _text, root = _asset(name, *required)
        for element in root.iter():
            if element.get("data-surface") == "true":
                assert contrast_ratio("#22211f", element.get("fill", "")) >= 4.5
            if element.get("data-series") is not None:
                assert element.get("aria-label")
                assert contrast_ratio(element.get("fill", ""), "#f6f1e8") >= 3
