from __future__ import annotations

from saliencegate.signals.base import (
    AbstentionReason,
    DetectionContext,
    DetectionInputError,
    DetectionOutcome,
    DetectionStatus,
    DetectorContractError,
    DetectorEvaluation,
    DeterministicSignalExtractor,
    ExtractionReport,
    SignalDetector,
    validate_detection_context,
)
from saliencegate.signals.fingerprints import (
    ActionFingerprint,
    FailureFingerprint,
    FingerprintUnavailableError,
    NormalizedTestFailure,
    ShellActionEvidence,
    TestFailureEvidence,
    TestReport,
    TestReportEvidence,
    TestReportStatus,
    ToolOutcome,
    ToolOutcomeEvidence,
    ToolOutcomeStatus,
    action_fingerprint,
    classify_test_report,
    classify_tool_outcome,
    failure_fingerprint,
    normalize_test_id,
    parse_test_report,
    parse_tool_outcome,
)
from saliencegate.signals.repetition import (
    RepeatedActionDetector,
    RepeatedFailureDetector,
    RepetitionConfig,
)
from saliencegate.signals.test_failures import TestFailureDetector
from saliencegate.signals.tool_errors import ToolErrorDetector

__all__ = [
    "AbstentionReason",
    "ActionFingerprint",
    "DetectionContext",
    "DetectionInputError",
    "DetectionOutcome",
    "DetectionStatus",
    "DetectorContractError",
    "DetectorEvaluation",
    "DeterministicSignalExtractor",
    "ExtractionReport",
    "FailureFingerprint",
    "FingerprintUnavailableError",
    "NormalizedTestFailure",
    "RepeatedActionDetector",
    "RepeatedFailureDetector",
    "RepetitionConfig",
    "ShellActionEvidence",
    "SignalDetector",
    "TestFailureDetector",
    "TestFailureEvidence",
    "TestReport",
    "TestReportEvidence",
    "TestReportStatus",
    "ToolErrorDetector",
    "ToolOutcome",
    "ToolOutcomeEvidence",
    "ToolOutcomeStatus",
    "action_fingerprint",
    "classify_test_report",
    "classify_tool_outcome",
    "failure_fingerprint",
    "normalize_test_id",
    "parse_test_report",
    "parse_tool_outcome",
    "validate_detection_context",
]
