"""Provider-neutral local capture contracts.

The package root is intentionally lazy.  Provider hooks import focused capture
submodules, and eagerly constructing every public report and normalization model
would add unrelated work to each short-lived hook process.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from saliencegate.capture.adapters import (
        CAPTURE_ADAPTER_PROTOCOL_VERSION,
        CaptureAdapter,
        CaptureAdapterCapabilities,
        CaptureAdapterContractError,
        validated_capture_adapter,
    )
    from saliencegate.capture.capabilities import (
        CapabilitySupport,
        CaptureCapabilityError,
        CaptureCapabilityManifest,
        CaptureCapabilityRegistry,
        CaptureProfile,
        CompatibilityStatus,
        capture_capability_digest,
        capture_profile,
        classify_capture_compatibility,
        load_capture_capability_registry,
        validate_capture_capability_binding,
    )
    from saliencegate.capture.connections import (
        CaptureConnectionSummary,
        CaptureSessionInventory,
        CaptureSessionSummary,
    )
    from saliencegate.capture.delete import (
        CaptureDeleteDisposition,
        CaptureProjectDeleteReceipt,
        CaptureSessionDeleteReceipt,
        delete_capture_project,
        delete_capture_session,
    )
    from saliencegate.capture.identities import CaptureDigestContext, CaptureIdentityError
    from saliencegate.capture.locations import (
        CaptureLocationError,
        CaptureStoreLocations,
        resolve_capture_store_locations,
    )
    from saliencegate.capture.migrations import (
        CaptureMigrationError,
        CaptureMigrationIntegrityError,
        CaptureMigrationReceipt,
        CaptureSchemaTooNewError,
        initialize_capture_store,
    )
    from saliencegate.capture.normalization import (
        CaptureDetectorEvidence,
        CaptureNormalization,
        CaptureNormalizationCounts,
        CaptureNormalizationDiagnostic,
        CaptureNormalizationDiagnosticCode,
        CaptureNormalizationError,
        normalize_capture_session_snapshot,
        verify_capture_normalization,
    )
    from saliencegate.capture.publication import (
        CaptureIntakeAuthenticationError,
        authenticate_capture_intake,
        verify_capture_intake_authentication,
    )
    from saliencegate.capture.report import (
        CAPTURE_SESSION_REPORT_SCHEMA_VERSION,
        CaptureReportCounts,
        CaptureReportCoverage,
        CaptureReportDetector,
        CaptureReportError,
        CaptureReportHeadline,
        CaptureReportHealthCount,
        CaptureReportInterval,
        CaptureReportLimit,
        CaptureSessionReport,
        CaptureSpoolReportStatus,
        build_capture_session_report,
        decode_capture_session_report,
        encode_capture_session_report,
        render_capture_session_report_human,
        render_capture_session_report_json,
    )
    from saliencegate.capture.schema import (
        CAPTURE_NATIVE_JSON_LIMITS,
        MAX_CAPTURE_EVENT_BYTES,
        MAX_CAPTURE_NATIVE_BYTES,
        CaptureActionFinishedIntake,
        CaptureActionStartedIntake,
        CaptureControllerFailedIntake,
        CaptureEvent,
        CaptureIntake,
        CaptureJSONLimits,
        CapturePermissionDeniedIntake,
        CaptureSchemaError,
        CaptureSessionFinishedIntake,
        CaptureSessionStartedIntake,
        CaptureSubagentFinishedIntake,
        CaptureSubagentStartedIntake,
        CaptureTurnFinishedIntake,
        canonical_capture_event,
        canonical_capture_intake,
        load_capture_event,
        load_capture_intake,
        read_bounded_json,
        validate_capture_event,
        validate_capture_intake,
    )
    from saliencegate.capture.scopes import (
        MAX_GLOBAL_CHILDREN_PER_PARENT,
        MAX_GLOBAL_EXCLUSIONS_PER_PARENT,
        MAX_GLOBAL_HEALTH_COUNT,
        MAX_GLOBAL_INSTALLATION_GENERATION,
        CaptureConnectionScope,
        CaptureGlobalChildBinding,
        CaptureGlobalChildIdentity,
        CaptureGlobalExclusionBinding,
        CaptureGlobalHealthCode,
        CaptureGlobalHealthCounter,
        CaptureGlobalParentRegistration,
        CaptureGlobalParentState,
        CaptureGlobalParentSummary,
        CaptureGlobalParentTransition,
        CaptureGlobalProvider,
        CaptureGlobalScopeError,
        capture_global_provider_profile,
        derive_global_child_identity,
        derive_global_config_root_digest,
        derive_global_parent_id,
    )
    from saliencegate.capture.sessions import (
        CaptureHumanSessionId,
        CaptureSessionSnapshot,
        CaptureSessionSnapshotError,
        CaptureSnapshotEvent,
        CaptureSnapshotHealth,
        verify_capture_session_snapshot,
    )
    from saliencegate.capture.spool import (
        MAX_CAPTURE_SPOOL_BYTES,
        MAX_CAPTURE_SPOOL_EVENTS,
        CaptureSpool,
        CaptureSpoolDrainReceipt,
        CaptureSpoolEnqueueReceipt,
        CaptureSpoolError,
        CaptureSpoolHealth,
        CaptureSpoolIntegrityError,
        CaptureSpoolMaintenance,
        CaptureSpoolObservation,
        CaptureSpoolObservationError,
        CaptureSpoolUnavailableError,
        admit_capture_intake,
        verify_capture_spool_observation,
    )
    from saliencegate.capture.store import (
        MAX_CAPTURE_EVENTS_PER_SESSION,
        CaptureAdmissionSource,
        CaptureAppendDisposition,
        CaptureAppendReceipt,
        CaptureConnectionRegistration,
        CaptureConnectionState,
        CaptureConnectionTransition,
        CaptureSessionState,
        CaptureSessionVerification,
        CaptureStore,
        CaptureStoreBusyError,
        CaptureStoreClosedError,
        CaptureStoreError,
        CaptureStoreIntegrityError,
        CaptureStoreMode,
        CaptureStoreStateError,
    )
    from saliencegate.capture.transport import (
        MAX_CAPTURE_TRANSPORT_CHUNKS_PER_SESSION,
        CaptureTransportChunk,
        CaptureTransportDisposition,
        CaptureTransportError,
        CaptureTransportReceipt,
        validate_capture_transport_chunk,
    )

_EXPORT_GROUPS: Final[dict[str, tuple[str, ...]]] = {
    "saliencegate.capture.adapters": (
        "CAPTURE_ADAPTER_PROTOCOL_VERSION",
        "CaptureAdapter",
        "CaptureAdapterCapabilities",
        "CaptureAdapterContractError",
        "validated_capture_adapter",
    ),
    "saliencegate.capture.capabilities": (
        "CapabilitySupport",
        "CaptureCapabilityError",
        "CaptureCapabilityManifest",
        "CaptureCapabilityRegistry",
        "CaptureProfile",
        "CompatibilityStatus",
        "capture_capability_digest",
        "capture_profile",
        "classify_capture_compatibility",
        "load_capture_capability_registry",
        "validate_capture_capability_binding",
    ),
    "saliencegate.capture.connections": (
        "CaptureConnectionSummary",
        "CaptureSessionInventory",
        "CaptureSessionSummary",
    ),
    "saliencegate.capture.delete": (
        "CaptureDeleteDisposition",
        "CaptureProjectDeleteReceipt",
        "CaptureSessionDeleteReceipt",
        "delete_capture_project",
        "delete_capture_session",
    ),
    "saliencegate.capture.identities": (
        "CaptureDigestContext",
        "CaptureIdentityError",
    ),
    "saliencegate.capture.locations": (
        "CaptureLocationError",
        "CaptureStoreLocations",
        "resolve_capture_store_locations",
    ),
    "saliencegate.capture.migrations": (
        "CaptureMigrationError",
        "CaptureMigrationIntegrityError",
        "CaptureMigrationReceipt",
        "CaptureSchemaTooNewError",
        "initialize_capture_store",
    ),
    "saliencegate.capture.normalization": (
        "CaptureDetectorEvidence",
        "CaptureNormalization",
        "CaptureNormalizationCounts",
        "CaptureNormalizationDiagnostic",
        "CaptureNormalizationDiagnosticCode",
        "CaptureNormalizationError",
        "normalize_capture_session_snapshot",
        "verify_capture_normalization",
    ),
    "saliencegate.capture.publication": (
        "CaptureIntakeAuthenticationError",
        "authenticate_capture_intake",
        "verify_capture_intake_authentication",
    ),
    "saliencegate.capture.report": (
        "CAPTURE_SESSION_REPORT_SCHEMA_VERSION",
        "CaptureReportCounts",
        "CaptureReportCoverage",
        "CaptureReportDetector",
        "CaptureReportError",
        "CaptureReportHeadline",
        "CaptureReportHealthCount",
        "CaptureReportInterval",
        "CaptureReportLimit",
        "CaptureSessionReport",
        "CaptureSpoolReportStatus",
        "build_capture_session_report",
        "decode_capture_session_report",
        "encode_capture_session_report",
        "render_capture_session_report_human",
        "render_capture_session_report_json",
    ),
    "saliencegate.capture.schema": (
        "CAPTURE_NATIVE_JSON_LIMITS",
        "MAX_CAPTURE_EVENT_BYTES",
        "MAX_CAPTURE_NATIVE_BYTES",
        "CaptureActionFinishedIntake",
        "CaptureActionStartedIntake",
        "CaptureControllerFailedIntake",
        "CaptureEvent",
        "CaptureIntake",
        "CaptureJSONLimits",
        "CapturePermissionDeniedIntake",
        "CaptureSchemaError",
        "CaptureSessionFinishedIntake",
        "CaptureSessionStartedIntake",
        "CaptureSubagentFinishedIntake",
        "CaptureSubagentStartedIntake",
        "CaptureTurnFinishedIntake",
        "canonical_capture_event",
        "canonical_capture_intake",
        "load_capture_event",
        "load_capture_intake",
        "read_bounded_json",
        "validate_capture_event",
        "validate_capture_intake",
    ),
    "saliencegate.capture.sessions": (
        "CaptureHumanSessionId",
        "CaptureSessionSnapshot",
        "CaptureSessionSnapshotError",
        "CaptureSnapshotEvent",
        "CaptureSnapshotHealth",
        "verify_capture_session_snapshot",
    ),
    "saliencegate.capture.scopes": (
        "MAX_GLOBAL_CHILDREN_PER_PARENT",
        "MAX_GLOBAL_EXCLUSIONS_PER_PARENT",
        "MAX_GLOBAL_HEALTH_COUNT",
        "MAX_GLOBAL_INSTALLATION_GENERATION",
        "CaptureConnectionScope",
        "CaptureGlobalChildBinding",
        "CaptureGlobalChildIdentity",
        "CaptureGlobalExclusionBinding",
        "CaptureGlobalHealthCode",
        "CaptureGlobalHealthCounter",
        "CaptureGlobalParentRegistration",
        "CaptureGlobalParentState",
        "CaptureGlobalParentSummary",
        "CaptureGlobalParentTransition",
        "CaptureGlobalProvider",
        "CaptureGlobalScopeError",
        "capture_global_provider_profile",
        "derive_global_child_identity",
        "derive_global_config_root_digest",
        "derive_global_parent_id",
    ),
    "saliencegate.capture.spool": (
        "MAX_CAPTURE_SPOOL_BYTES",
        "MAX_CAPTURE_SPOOL_EVENTS",
        "CaptureSpool",
        "CaptureSpoolDrainReceipt",
        "CaptureSpoolEnqueueReceipt",
        "CaptureSpoolError",
        "CaptureSpoolHealth",
        "CaptureSpoolIntegrityError",
        "CaptureSpoolMaintenance",
        "CaptureSpoolObservation",
        "CaptureSpoolObservationError",
        "CaptureSpoolUnavailableError",
        "admit_capture_intake",
        "verify_capture_spool_observation",
    ),
    "saliencegate.capture.store": (
        "MAX_CAPTURE_EVENTS_PER_SESSION",
        "CaptureAdmissionSource",
        "CaptureAppendDisposition",
        "CaptureAppendReceipt",
        "CaptureConnectionRegistration",
        "CaptureConnectionState",
        "CaptureConnectionTransition",
        "CaptureSessionState",
        "CaptureSessionVerification",
        "CaptureStore",
        "CaptureStoreBusyError",
        "CaptureStoreClosedError",
        "CaptureStoreError",
        "CaptureStoreIntegrityError",
        "CaptureStoreMode",
        "CaptureStoreStateError",
    ),
    "saliencegate.capture.transport": (
        "MAX_CAPTURE_TRANSPORT_CHUNKS_PER_SESSION",
        "CaptureTransportChunk",
        "CaptureTransportDisposition",
        "CaptureTransportError",
        "CaptureTransportReceipt",
        "validate_capture_transport_chunk",
    ),
}

_EXPORTS: Final[dict[str, str]] = {
    name: module_name for module_name, names in _EXPORT_GROUPS.items() for name in names
}

__all__ = [
    "CAPTURE_ADAPTER_PROTOCOL_VERSION",
    "CAPTURE_NATIVE_JSON_LIMITS",
    "CAPTURE_SESSION_REPORT_SCHEMA_VERSION",
    "MAX_CAPTURE_EVENTS_PER_SESSION",
    "MAX_CAPTURE_EVENT_BYTES",
    "MAX_CAPTURE_NATIVE_BYTES",
    "MAX_CAPTURE_SPOOL_BYTES",
    "MAX_CAPTURE_SPOOL_EVENTS",
    "MAX_CAPTURE_TRANSPORT_CHUNKS_PER_SESSION",
    "MAX_GLOBAL_CHILDREN_PER_PARENT",
    "MAX_GLOBAL_EXCLUSIONS_PER_PARENT",
    "MAX_GLOBAL_HEALTH_COUNT",
    "MAX_GLOBAL_INSTALLATION_GENERATION",
    "CapabilitySupport",
    "CaptureActionFinishedIntake",
    "CaptureActionStartedIntake",
    "CaptureAdapter",
    "CaptureAdapterCapabilities",
    "CaptureAdapterContractError",
    "CaptureAdmissionSource",
    "CaptureAppendDisposition",
    "CaptureAppendReceipt",
    "CaptureCapabilityError",
    "CaptureCapabilityManifest",
    "CaptureCapabilityRegistry",
    "CaptureConnectionRegistration",
    "CaptureConnectionScope",
    "CaptureConnectionState",
    "CaptureConnectionSummary",
    "CaptureConnectionTransition",
    "CaptureControllerFailedIntake",
    "CaptureDeleteDisposition",
    "CaptureDetectorEvidence",
    "CaptureDigestContext",
    "CaptureEvent",
    "CaptureGlobalChildBinding",
    "CaptureGlobalChildIdentity",
    "CaptureGlobalExclusionBinding",
    "CaptureGlobalHealthCode",
    "CaptureGlobalHealthCounter",
    "CaptureGlobalParentRegistration",
    "CaptureGlobalParentState",
    "CaptureGlobalParentSummary",
    "CaptureGlobalParentTransition",
    "CaptureGlobalProvider",
    "CaptureGlobalScopeError",
    "CaptureHumanSessionId",
    "CaptureIdentityError",
    "CaptureIntake",
    "CaptureIntakeAuthenticationError",
    "CaptureJSONLimits",
    "CaptureLocationError",
    "CaptureMigrationError",
    "CaptureMigrationIntegrityError",
    "CaptureMigrationReceipt",
    "CaptureNormalization",
    "CaptureNormalizationCounts",
    "CaptureNormalizationDiagnostic",
    "CaptureNormalizationDiagnosticCode",
    "CaptureNormalizationError",
    "CapturePermissionDeniedIntake",
    "CaptureProfile",
    "CaptureProjectDeleteReceipt",
    "CaptureReportCounts",
    "CaptureReportCoverage",
    "CaptureReportDetector",
    "CaptureReportError",
    "CaptureReportHeadline",
    "CaptureReportHealthCount",
    "CaptureReportInterval",
    "CaptureReportLimit",
    "CaptureSchemaError",
    "CaptureSchemaTooNewError",
    "CaptureSessionDeleteReceipt",
    "CaptureSessionFinishedIntake",
    "CaptureSessionInventory",
    "CaptureSessionReport",
    "CaptureSessionSnapshot",
    "CaptureSessionSnapshotError",
    "CaptureSessionStartedIntake",
    "CaptureSessionState",
    "CaptureSessionSummary",
    "CaptureSessionVerification",
    "CaptureSnapshotEvent",
    "CaptureSnapshotHealth",
    "CaptureSpool",
    "CaptureSpoolDrainReceipt",
    "CaptureSpoolEnqueueReceipt",
    "CaptureSpoolError",
    "CaptureSpoolHealth",
    "CaptureSpoolIntegrityError",
    "CaptureSpoolMaintenance",
    "CaptureSpoolObservation",
    "CaptureSpoolObservationError",
    "CaptureSpoolReportStatus",
    "CaptureSpoolUnavailableError",
    "CaptureStore",
    "CaptureStoreBusyError",
    "CaptureStoreClosedError",
    "CaptureStoreError",
    "CaptureStoreIntegrityError",
    "CaptureStoreLocations",
    "CaptureStoreMode",
    "CaptureStoreStateError",
    "CaptureSubagentFinishedIntake",
    "CaptureSubagentStartedIntake",
    "CaptureTransportChunk",
    "CaptureTransportDisposition",
    "CaptureTransportError",
    "CaptureTransportReceipt",
    "CaptureTurnFinishedIntake",
    "CompatibilityStatus",
    "admit_capture_intake",
    "authenticate_capture_intake",
    "build_capture_session_report",
    "canonical_capture_event",
    "canonical_capture_intake",
    "capture_capability_digest",
    "capture_global_provider_profile",
    "capture_profile",
    "classify_capture_compatibility",
    "decode_capture_session_report",
    "delete_capture_project",
    "delete_capture_session",
    "derive_global_child_identity",
    "derive_global_config_root_digest",
    "derive_global_parent_id",
    "encode_capture_session_report",
    "initialize_capture_store",
    "load_capture_capability_registry",
    "load_capture_event",
    "load_capture_intake",
    "normalize_capture_session_snapshot",
    "read_bounded_json",
    "render_capture_session_report_human",
    "render_capture_session_report_json",
    "resolve_capture_store_locations",
    "validate_capture_capability_binding",
    "validate_capture_event",
    "validate_capture_intake",
    "validate_capture_transport_chunk",
    "validated_capture_adapter",
    "verify_capture_intake_authentication",
    "verify_capture_normalization",
    "verify_capture_session_snapshot",
    "verify_capture_spool_observation",
]

if len(_EXPORTS) != len(__all__) or frozenset(_EXPORTS) != frozenset(__all__):
    raise RuntimeError("capture public API export map is invalid")


def __getattr__(name: str) -> object:
    """Resolve and cache one declared public export from its owning submodule."""

    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(frozenset(globals()).union(__all__))
